### ISSUE TITLE
Detached HTMLElement

### ISSUE THREAD

**Issue by q1998763** [pixijs/html-text#19]
If I use "setInterval" to update text, The DOM Nodes has been increasing.
![image](https://user-images.githubusercontent.com/14989849/172285372-28f4dcb5-1419-4e6f-a10a-d6d058d1867b.png)

**Comment by bigtimebuddy** [comment]
You're right, this plugin could do a better job of reusing DOM elements that it creates.

One important note, is that HTMLText (or PixiJS's Text) are not well suited to being constantly updated (say on an setInterval). Because these elements write to a canvas element and then constant upload to the GPU, it can throttle the performance of your PixiJS content. It's better to use BitmapText instead.
