### ISSUE TITLE
Custom fonts not working

### ISSUE THREAD

**Issue by dnlmzw** [pixijs/html-text#2]
I'm not able to show custom fonts with HTML Text. If I replace `PIXI.HTMLText` with `PIXI.Text` my custom font is showing properly.

```
const app = new PIXI.Application({
  width: window.innerWidth,
  height: window.innerHeight,
  resolution: window.devicePixelRatio,
  autoDensity: true,
  transparent: true,
  resizeTo: window,
});

const textStyle = new PIXI.TextStyle({
  fontFamily: ["Work Sans", "Courier New", "sans-serif"],
  fontSize: 16 * 4,
  wordWrapWidth: window.innerWidth / 2,
  wordWrap: true,
  fontWeight: 350,
  fill: 0xffffff,
});

const title = new PIXI.HTMLText(
  "<strong>Custom</strong> font family",
  textStyle
);
title.x = 100;
title.y = 100;
app.stage.addChild(title);
```

Shows the fallback font:
<img width="917" alt="PIXI HTMLText" src="https://user-images.githubusercontent.com/960055/87403350-0b761400-c5bd-11ea-8dd9-21ffc19b31b7.png">

If I replace `new PIXI.HTMLText` with `new PIXI.Text` my fonts are showing properly:
<img width="1006" alt="PIXI Text" src="https://user-images.githubusercontent.com/960055/87403359-0ca74100-c5bd-11ea-9bb0-adbbbc2b6fb9.png">

**Comment by bigtimebuddy** [comment]
What if you use a string instead of an array for the fontFamily? I’m not sure I’m handling array input, but should be an easy fix.

**Comment by bigtimebuddy** [comment]
Also, are you sure the font is preloaded by the time you use it?

**Comment by bigtimebuddy** [comment]
Yup, this is a bug: https://jsfiddle.net/bigtimebuddy/o4s61bjy/

I think it's because SVG handles custom fonts slightly different. I need to provide a way to handle this. Thanks for reporting.

**Comment by dnlmzw** [comment]
You're welcome and thanks for looking into this. I tried using a string which didn't work. I also tried using .updateText() which also didn't do anything, so looks like the SVG error could be the thing.

**Comment by bigtimebuddy** [comment]
Okay, I did some digging and this _seems_ like it should work, but it's a little more complicated. Basically, I'm rendering the HTML text to SVG internally and that doesn't share fonts with the main document. Also, rendering it with canvas doesn't support external file requests like fonts. The only way I was able to get this to work was to add a base64 encoded font to the internal SVG.

Likely, this is going to have to be a new feature because I'm not sure if there's anyway I can do this operation automatically.

I added some notes to the readme to say that it only supports web-safe fonts.

[Related issue](https://stackoverflow.com/questions/42402584/how-to-use-google-fonts-in-canvas-when-drawing-dom-objects-in-svg)
